[alias]
stage1 = "test -p stage1"
stage2 = "test -p stage2"
stage3 = "test -p stage3"
stage4 = "test -p stage4"
stage5 = "test -p stage5"
stage6 = "test -p stage6"
stage7 = "test -p stage7"
stage8 = "test -p stage8"
stage9 = "test -p stage9"
stage10 = "test -p stage10"
stage11 = "test -p stage11"
stage12 = "test -p stage12"
stage13 = "test -p stage13"
test-all = "test --workspace"
