[alias]
stage1 = "test -p stage1"
stage2 = "test -p stage2"
stage3 = "test -p stage3"
stage6 = "test -p stage6"
stage7 = "test -p stage7"
stage8 = "test -p stage8"
stage9 = "test -p stage9"
test-all = "test --workspace"
